name: Keep Codespace Alive

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Commit a dummy change
        run: |
          touch dummyfile
          git add .
          git commit -m "Keep codespace alive"
          git push
