name: Keep Codespace Alive

on:
  schedule:
    - cron: "*/5 * * * *" # Alle 25 Minuten ausführen
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Konfiguriere Git
        run: |
          git config --global user.email "bennofromme@gmail.com"
          git config --global user.name "BigB132"

      - name: Erstelle Dummy-Datei und committe bei Änderungen
        run: |
          touch dummyfile
          git add dummyfile
          git diff-index --quiet HEAD || git commit -m "Keep codespace alive"
          git push
      - name: Push Änderungen
        run: git push
