name: Keep Codespace Alive

on:
  schedule:
    - cron: "*/25 * * * *"
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Konfiguriere Git
        run: |
          git config --global user.email "bennofromme@gmail.com"
          git config --global user.name "BigB132"

      - name: Erstelle Dummy-Datei
        run: |
          touch dummyfile
          git add .
          git commit -m "Keep codespace alive"

      - name: Push Änderungen
        run: git push
